from __future__ import annotations

from typing import Protocol

from app.application.dto.stage_execution_result import StageExecutionResult


class WorkflowStagePort(Protocol):
    """External stage operations available to the workflow orchestrator."""

    async def download(self, job_id: str) -> StageExecutionResult: ...

    async def analyze(self, job_id: str) -> StageExecutionResult: ...

    async def analyze_cdha(self, job_id: str) -> StageExecutionResult: ...

    async def capture_screenshots(self, job_id: str) -> StageExecutionResult: ...

    async def approve_review(self, job_id: str) -> StageExecutionResult: ...

    async def facebook(self, job_id: str) -> StageExecutionResult: ...

    async def reconcile_facebook(self, job_id: str) -> StageExecutionResult: ...

    async def extract_permalink(self, job_id: str) -> StageExecutionResult: ...

    async def add_permalink_comment(self, job_id: str) -> StageExecutionResult: ...
