from __future__ import annotations

from enum import StrEnum


class JobStatus(StrEnum):
    """Authoritative persisted status for the end-to-end workflow and its queue boundary."""

    CREATED = "CREATED"
    PENDING = "PENDING"
    ACQUIRING_BROWSER_LOCK = "ACQUIRING_BROWSER_LOCK"
    WAITING_FOR_BROWSER_LOCK = "WAITING_FOR_BROWSER_LOCK"
    RUNNING = "RUNNING"
    DOWNLOADREEL_RUNNING = "DOWNLOADREEL_RUNNING"
    DOWNLOADED = "DOWNLOADED"
    DOWNLOADREEL_FAILED = "DOWNLOADREEL_FAILED"
    GEMINI_OPENING = "GEMINI_OPENING"
    NEEDS_GEMINI_LOGIN = "NEEDS_GEMINI_LOGIN"
    GEMINI_GENERATING = "GEMINI_GENERATING"
    CLINICAL_FACTORS_GENERATED = "CLINICAL_FACTORS_GENERATED"
    GEMINI_FAILED = "GEMINI_FAILED"
    AI_ANALYZING = "AI_ANALYZING"
    AI_FAILED = "AI_FAILED"
    CDHA_OPENING = "CDHA_OPENING"
    NEEDS_CDHA_LOGIN = "NEEDS_CDHA_LOGIN"
    CDHA_UPLOADING = "CDHA_UPLOADING"
    CDHA_ANALYZING = "CDHA_ANALYZING"
    CDHA_ANALYZED = "CDHA_ANALYZED"
    CDHA_FAILED = "CDHA_FAILED"
    SCREENSHOTS_CAPTURING = "SCREENSHOTS_CAPTURING"
    SCREENSHOTS_CAPTURED = "SCREENSHOTS_CAPTURED"
    SCREENSHOTS_FAILED = "SCREENSHOTS_FAILED"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FACEBOOK_PREPARING = "FACEBOOK_PREPARING"
    WAITING_FOR_AUTH_REVIEW = "WAITING_FOR_AUTH_REVIEW"
    FACEBOOK_WAITING_FOR_MANUAL_REVIEW = "FACEBOOK_WAITING_FOR_MANUAL_REVIEW"
    FACEBOOK_PUBLISHING = "FACEBOOK_PUBLISHING"
    FACEBOOK_PUBLISHED = "FACEBOOK_PUBLISHED"
    FACEBOOK_PUBLISH_FAILED = "FACEBOOK_PUBLISH_FAILED"
    FACEBOOK_PUBLISH_UNCERTAIN = "FACEBOOK_PUBLISH_UNCERTAIN"
    PUBLISH_RECONCILIATION_REQUIRED = "PUBLISH_RECONCILIATION_REQUIRED"
    FACEBOOK_SUBMITTED_UNCONFIRMED_EXHAUSTED = "FACEBOOK_SUBMITTED_UNCONFIRMED_EXHAUSTED"
    POSSIBLE_DUPLICATE_REQUIRES_MANUAL_REVIEW = "POSSIBLE_DUPLICATE_REQUIRES_MANUAL_REVIEW"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    POST_URL_EXTRACTING = "POST_URL_EXTRACTING"
    POST_URL_EXTRACTED = "POST_URL_EXTRACTED"
    POST_URL_EXTRACTION_FAILED = "POST_URL_EXTRACTION_FAILED"
    COMMENT_ADDING = "COMMENT_ADDING"
    COMMENT_ADDED = "COMMENT_ADDED"
    COMMENT_FAILED = "COMMENT_FAILED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRY_PENDING = "RETRY_PENDING"
    RETRYABLE = "RETRYABLE"
    BLOCKED = "BLOCKED"
    BLOCKED_USER_APPROVAL = "BLOCKED_USER_APPROVAL"
    CANCELLED = "CANCELLED"


# Compatibility name used by the verified legacy workflow. This is an alias,
# not a second enum.
WorkflowStatus = JobStatus
